sudo: required

language: ruby

services:
  - docker

before_install:
  - docker info
  - docker build --rm=false -t nothing-to-see-here .

script:
  - docker run -t nothing-to-see-here gdal-config --version
